### ISSUE TITLE
handshake failed due to unexpected packet format

### ISSUE THREAD

**Issue by adamosoftware** [okta/samples-aspnet#10]
Hi there, I cloned this repo and tried to run myself locally. I'm getting this error when I try to visit http://localhost:8080/Account/Login

![image](https://user-images.githubusercontent.com/4549398/50378579-7e96ee80-0603-11e9-9cc7-b3998a50948b.png)

The only changes I made are
- added my client/secret/domain to web.config. I wasn't sure about the domain because I don't see that anywhere in Okta dashboard. I assumed localhost:8080 was okay for domain.
- had to update a couple packages Microsoft.CodeDom.Providers.DotNetCompilerPlatform and Microsoft.Net.Compilers due to Roslyn issue when debugging in visual studio (idea came from here: https://stackoverflow.com/a/38668274/2023653)

**Comment by nbarbettini** [comment]
@adamosoftware The domain in web.config should be your Okta domain. From your screenshot, I am guessing it is `https://dev-770332.oktapreview.com`. You can see/copy it from the Dashboard view of the Okta console, in the top right corner.

Try updating that and let me know if it solves the server error.

**Comment by adamosoftware** [comment]
Thank you! I didn't realize significance of that Url until you called attention to it. I got a bit further, but am seeing this now:

![image](https://user-images.githubusercontent.com/4549398/50406383-6903ff00-0792-11e9-9e8c-3dacd7bfdea5.png)

**Comment by nbarbettini** [comment]
Ah, just realized that our instructions may be incomplete. Can you link me to the instructions you've been following so far?

Try enabling Implicit (Hybrid) > Allow ID Token in the Okta console for this application. This step is only required for ASP.NET MVC due to a quirk of the ASP.NET internals. If that works for you, I'll make sure we get the docs updated so this step is clear.

**Comment by adamosoftware** [comment]
hey there, I wasn't really following any instructions, really -- just cloned the repo and tried to run it. But I found the repo from here: https://developer.okta.com/code/dotnet/aspnet/

Your suggestion worked about changing that setting thank you!
