### ISSUE TITLE
Response status code does not indicate success

### ISSUE THREAD

**Issue by AndrewHexagon** [okta/samples-aspnet#11]
I am getting started with Okta and want to utilize your example to leverage Okta to successfully authorize my applications but I'm having difficulty.

When I start the application, the menu and login button both aren't visible. ![okta_aspnet_no_menu](https://user-images.githubusercontent.com/46489938/51707875-f16efd00-1fe7-11e9-9bc5-fe65a0ebbe8a.JPG) When I manually add the login button and click it I get the error "Response status code does not indicate success: 401 (Unauthorized)."

I have been reading and following the remediation examples in [this thread](https://devforum.okta.com/t/error-with-okta-net-mvc-example/2132/18), but nothing has worked yet.

**Comment by laura-rodriguez** [comment]
Hi @AndrewHexagon,

If your style is broken, I am wondering if you have updated `bootstrap.`
What sample are you working on? `okta-hosted-login`?

**Comment by AndrewHexagon** [comment]
I WAS working on Okta-hosted-login. I started self-hosted-login and I don’t get the “Response status code” error anymore!

I updated all the packages in Nuget, and it’s using bootstrap 4.2.1.

In both projects the menu doesn’t appear at all. The entire navbar-header does not display OOTB, I have to manually hand jam the Login actionLink for it to display.

Now that I’m using the self-hosted-login, when I click on the login link I get  “unable to connect to server” error which sounds like configuration issues on my end.

**Comment by laura-rodriguez** [comment]
These projects are created using the default Visual Studio boilerplate which is using a specific version of `bootstrap`. If you update it, you might have some styles broken. You can opt to use the current bootstrap version or update it and fix the style issues.
The idea of these projects is to show how to use the Okta ASP.NET SDK so you can port it easily in your personal projects 😄 .

Regarding the `unable to connect to server` error, it sounds as configuration error in your end, as you mentioned. Let me know how I can help you to configure the Okta middleware. If you are able to share your code I could take a look.

Did you find the [quickstart](https://developer.okta.com/quickstart/#/okta-sign-in-page/dotnet/aspnet4) clear enough to configure a project from scratch?

**Comment by AndrewHexagon** [comment]
Ok. I reverted the project and the menu started to work.

But I still get this error message when I try to log in.

SEC7120: [CORS] The origin 'http://localhost:8080' did not find 'http://localhost:8080' in the Access-Control-Allow-Origin response header for cross-origin resource at 'https://hexagon-dev-729648.oktapreview.com/api/v1/authn'

I do have my trusted origins set like so… Do I need to add code to the okta-aspnet-mvc-exmaple to enable CORS on the project?


[cid:image001.png@01D4B498.32E67620]

**Comment by laura-rodriguez** [comment]
I think you are using the wrong `OktaDomain`. Isn't your url `https://dev-729648.oktapreview.com/` instead of `https://hexagon-dev-729648.oktapreview.com/`?

**Comment by AndrewHexagon** [comment]
That worked, thank you!

**Comment by laura-rodriguez** [comment]
I'm glad it's working 🎉. I'll close the issue, but feel free to reopen if you need it. Happy coding!
