### ISSUE TITLE
Okta-Aspnet-Mvc-Example Just Spinning on Login

### ISSUE THREAD

**Issue by eralston** [okta/samples-aspnet#34]
I've pulled down the Okta-Aspnet-Mvc-Example and filled in the web.config with values from the Okta developer console (ClientId, ClientSecret, Domain). 

Unfortunately, now the only thing that happens it attempts to authenticate is bouncing back and forth between my app and Okta. I've tried building up my own project from the ASP.Net Getting Started guide and it has the same result.

Please: Any possible explanation or help?

**Comment by laura-rodriguez** [comment]
Hi @eralston,

This can be related to your configuration. Have you followed the step-by-step instructions from our [guides](https://developer.okta.com/docs/guides/sign-into-web-app/aspnet/before-you-begin/)?
Make sure your configuration is correct.

**Comment by eralston** [comment]
Thank you for your response @laura-rodriguez!

Trying the instructions in that guide verbatim causes a new problem. When I setup an app per the instructions, replacing the ClientID and ClientSecret in my web.config, I get the following error:

"OpenIdConnectMessage.Error was not null, indicating an error. Error: 'unsupported_response_type'. Error_Description (may be empty): 'The response type is not supported by the authorization server. Configured response types: [code].'. Error_Uri (may be empty): ''."

I am able to go into the application settings and toggle the checkboxes to thus:

![image](https://user-images.githubusercontent.com/636858/64047702-5f524880-cb24-11e9-8bbd-bf350f4ae19f.png)

This configuration will cause the endless spin; however, the other configurations seem to error out. Any further suggestions? 

Thank you very much!
Erik

**Comment by laura-rodriguez** [comment]
Can you post your web.config and your startup class? Please, hide your secrets such as the clientId and ClientSecret :).

**Comment by laura-rodriguez** [comment]
Closing due inactivity. Feel free to reopen if this is still an issue.
