### ISSUE TITLE
404 Error in okta-hosted-login sample from Forgot Password flow

### ISSUE THREAD

**Issue by scraperg** [okta/samples-aspnet#37]
Hi,

I have configured the okta-hosted-login sample and am able to log in. Everything seems to work, except for the last step of the Forgot Password flow.

After going through the "Forgot Password?" email/security question/new password flow, I'm redirected back to `http://localhost:8080/authorization-code/callback?iss=...` , which results in a 404 ASP.NET error:

```
The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /authorization-code/callback
```

I have the following set in Web.config, and it works for Login. Just not the redirect from Forgot Password.

```
<add key="okta:RedirectUri" value="http://localhost:8080/authorization-code/callback" />
```

Any suggestions on how to successfully complete Forgot Password in the sample app?

Thanks.

**Comment by laura-rodriguez** [comment]
Hi @scraperg ,

If you are using the okta-hosted login, you can use the "Need help signing in?" link that provides you an option for forgotten passwords. Let me know if it helps.

![image](https://user-images.githubusercontent.com/16751130/68407924-6617c000-0152-11ea-893b-f5cd0d71a393.png)

**Comment by scraperg** [comment]
Hi Laura,

The 404 error occurs _after_ clicking "Need help signing in?", and going through the Forgot Password process. I get the password reset email, and can successfully update my password, etc... But at the end of it all, it redirects back to an invalid URL on my web server (http://localhost:8080/authorization-code/callback?iss=...).

And just to re-iterate, I can successfully log in to my app using the Okta hosted login page. So I think my configuration is okay. The 404 only occurs at the very end of the Forgot Password flow, when Okta redirects back to my app.

Thanks.

**Comment by laura-rodriguez** [comment]
Hi @scraperg ,

Thanks for the info! I wasn't able to reproduce the same invalid URL you got. 

Where exactly did you click to get redirected to that invalid URL?  Was it after clicking "back to sign in"?:
![image](https://user-images.githubusercontent.com/16751130/69570490-f09f5280-0f8d-11ea-8fad-201405b6dc9c.png)

or, right after you changed your password and you successfully clicked "Reset my password"?:
![image](https://user-images.githubusercontent.com/16751130/69570651-378d4800-0f8e-11ea-84e4-cd98eb41b581.png)

**Comment by dnvnjstc** [comment]
I am unfortunately also experiencing this issue, but only under a specific scenario where the password reset request crosses different browsers.

Here is a reproducible flow:
1. User navigates to my site from **Browser A**, which redirects and displays the okta-hosted login page.
2. User clicks on '_Need help signing in?_' link from **Browser A**
3. User clicks '_Forgot Password_' link from **Browser A**
4. User enters email address, and clicks '_Reset via Email_' link within **Browser A**
5. User opens email in a _different_ browser (**Browser B**)
6. User clicks reset password link in email within **Browser B** 
7. The '_Reset your Okta password_' form displays in **Browser B**
8. User enters and repeats New password, and clicks '_Reset Password_' button in **Browser B**
9. User sees 404 error when middleware navigates to the callback endpoint (http://localhost:8080/authorization-code/callback?iss=...) within **Browser B**

I can confirm that it does successfully complete the password reset flow if everything is initiated _within the same browser_.

**Comment by dnvnjstc** [comment]
Not only is the forgot password flow failing when performed across browsers, this flow is also failing during self-service registration.

**Comment by laura-rodriguez** [comment]
Hi @dnvnjstc ,

Thanks for the report and the detailed steps to reproduce it ❤️ . We have a task in our backlog to review this, but unfortunately, we didn't have the time to work on this yet. 

Can you please add more details to describe the self-service registration issue?

**Comment by dnvnjstc** [comment]
Hi @laura-rodriguez,

Certainly! Here is a reproducible flow for self-service registration with email verification enabled:

1. User navigates to my site from **Browser A**, which redirects and displays the okta-hosted login page.
2. User clicks on '_Don't have an account? Sign up_' link from **Browser A**
3. User fills registration form and clicks '_Register_' button within **Browser A**
4. Message displays stating that verification email has been sent within **Browser A**
5. User opens email in a _different_ browser (**Browser B**)
6. User clicks verify link in email within **Browser B**
7. User sees 404 error when middleware navigates to the callback endpoint (http://localhost:8080/authorization-code/callback?iss=...) within **Browser B**

**Comment by dnvnjstc** [comment]
Hi @laura-rodriguez,

Is there a link to the ticket that I can track? This is a bit of a roadblock for us at the moment and we are trying to estimate our release.

**Comment by laura-rodriguez** [comment]
Hi @dnvnjstc ,

Unfortunately I can't provide you a link because it is internal.

Let me discuss with the team to see if we can prioritize this any time soon.

**Comment by bryanapellanes-okta** [comment]
@scraperg @dnvnjstc 
Can you confirm that you are still seeing this behavior?

I have been reviewing this issue in an attempt to reproduce as described.  I haven't been able to reproduce the exact behavior, however, I did uncover some potential issues following the documentation verbatim to set up the sample project.

In my own testing the settings in the developer console should look similar to the following for all flows to function as expected, note the "Logout redirect URIs" and "Initiate login URI":
![image](https://user-images.githubusercontent.com/63638027/81114256-87c1ec00-8ed6-11ea-9342-5e4001812707.png)

**Comment by bryanapellanes-okta** [comment]
Closing issue after 2 weeks no response.

**Comment by anricoj1** [comment]
Has this issue actually been solved? I'm currently experiencing this same issue 2 years later.
