### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized) using production Okta account

### ISSUE THREAD

**Issue by HengkyChandra** [okta/samples-aspnet#38]
I am trying to get the quickstart demo to work in our production Okta account.   It works fine with our developer account but throws a error message when trying to redirect to Okta login page with "Response status code does not indicate success: 401 (Unauthorized)".  Both accounts are setup the same.

**Comment by HengkyChandra** [comment]
Hi @laura-rodriguez there is no authorization servers in my Okta prod. I suspect Okta.AspNet only support authorization code only, so it can not work well using implicit id token.

**Comment by laura-rodriguez** [comment]
Ok, then I suspect that might be the issue.

When you set up your Okta configuration, set `AuthorizationServerId = ""`. The default value for this property is default: https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet.Abstractions/OktaWebOptions.cs#L30, but you don't want to use that.
Let me know if it helps.

**Comment by makemeafirewall** [comment]
@laura-rodriguez Thanks a LOT for the last comment on this issue!!! Helped me a LOT!
