### ISSUE TITLE
How to invalidate ASP.NET cookie when user signs out of Okta dashboard?

### ISSUE THREAD

**Issue by thiag0** [okta/samples-aspnet#46]
Hi, does this library provide a way for invalidate the ASP.NET cookie if the user logs out directly in the Okta dashboard? 

The scenario is the following - A user tries to access the ASP.NET application and is redirected to Okta for login. They authenticate and then are redirected back to the ASP.NET application. The user then opens the Okta dashboard in a new browser window, and logs out of Okta (not the ASP.NET app). When the user tries to access the ASP.NET application after Okta logout, it still sees a valid cookie and allows them to access the application.

**Comment by bryanapellanes-okta** [comment]
@thiag0,
Thank you for your question!

I believe the answer to your question is yes; however, I will investigate further to get you a more definitive answer.  Realistically, I think the answer depends on the overall state of all login sessions for the user.  Stay tuned!

**Comment by thiag0** [comment]
> @thiag0,
> Thank you for your question!
> 
> I believe the answer to your question is yes; however, I will investigate further to get you a more definitive answer. Realistically, I think the answer depends on the overall state of all login sessions for the user. Stay tuned!

Thank you @bryanapellanes-okta, I look forward to your response.

**Comment by bryanapellanes-okta** [comment]
@thiag0, 
> Hi, does this library provide a way for invalidate the ASP.NET cookie if the user logs out directly in the Okta dashboard?
> 
> The scenario is the following - A user tries to access the ASP.NET application and is redirected to Okta for login. They authenticate and then are redirected back to the ASP.NET application. The user then opens the Okta dashboard in a new browser window, and logs out of Okta (not the ASP.NET app). When the user tries to access the ASP.NET application after Okta logout, it still sees a valid cookie and allows them to access the application.

After some testing I've determined that my initial response is incorrect; the behavior is just as you describe.  The ASP.NET application is unaware that the user has logged out of the Okta dashboard and their ASP.NET session is still authenticated even after logging out of the Okta dashboard.  The library does not currently support invalidating the ASP.NET session cookie when a user logs out of the Okta dashboard.

Hope this helps, let me know if I've misinterpreted your question.

Thanks!
Bryan

**Comment by bryanapellanes-okta** [comment]
Feel free to reopen this issue if I've not answered your question.

**Comment by thiag0** [comment]
@brianhuang-okta Thanks for your response and confirmation of this issue. Does Okta have any recommendation or best practice for how to handle this scenario? Any further help would be much appreciated.

**Comment by bryanapellanes-okta** [comment]
@thiag0,
I'll inquire internally to see if we can provide additional guidance.

**Comment by bryanapellanes-okta** [comment]
@thiag0,
I've inquired internally and found you may be able to use the [events api](https://developer.okta.com/docs/reference/api/events/) or [system log](https://developer.okta.com/docs/reference/api/system-log/)  api leveraging the `user.session.end` [event type](https://developer.okta.com/docs/reference/api/event-types/?q=event-hook-eligible#catalog).  Make sure to consider [rate-limits](https://developer.okta.com/docs/concepts/event-hooks/#rate-limits) when evaluating this approach.

Hopefully this helps!  Thanks for using Okta!

**Comment by thiag0** [comment]
> @thiag0,
> I've inquired internally and found you may be able to use the [events api](https://developer.okta.com/docs/reference/api/events/) or [system log](https://developer.okta.com/docs/reference/api/system-log/) api leveraging the `user.session.end` [event type](https://developer.okta.com/docs/reference/api/event-types/?q=event-hook-eligible#catalog). Make sure to consider [rate-limits](https://developer.okta.com/docs/concepts/event-hooks/#rate-limits) when evaluating this approach.

@bryanapellanes-okta Thanks for the additional information, it certainly helps to know that there is something available but I'm not sure if it will solve our use case. 

In our implementation, the ASP.NET application is on our server, but the Okta org is managed and controlled by the client. My understanding of these APIs, is that it requires an API Token to be created within the Okta org, which is something the client will not provide to us due to security concerns. Is that a correct understanding? And if this is the case, is there any other suggested approaches available?

**Comment by bryanapellanes-okta** [comment]
> @thiag0,
> I've inquired internally and found you may be able to use the ~~[events api](https://developer.okta.com/docs/reference/api/events/)~~ [evnet hooks api](https://developer.okta.com/docs/reference/api/event-hooks/) or [system log](https://developer.okta.com/docs/reference/api/system-log/) api leveraging the `user.session.end` [event type](https://developer.okta.com/docs/reference/api/event-types/?q=event-hook-eligible#catalog). Make sure to consider [rate-limits](https://developer.okta.com/docs/concepts/event-hooks/#rate-limits) when evaluating this approach.
> 
> Hopefully this helps! Thanks for using Okta!

In my previous response I incorrectly linked to the events api where I should have linked to the [event hooks api](https://developer.okta.com/docs/reference/api/event-hooks/).  Hopefully, this helps.  Thanks!
